[versions]
kotlin = "1.9.10"
network-okhttp = "5.0.0-alpha.11"
network-retrofit = "2.9.0"
json-moshi = "1.15.0"

# [ https://github.com/Kotlin/kotlinx.coroutines ]
kotlin-coroutines-core = "1.7.3"

# [ https://github.com/Kotlin/kotlinx-datetime ]
kotlin-datetime = "0.4.1"

# [ https://github.com/orhanobut/logger ]
logger = "2.2.0"

# [ https://github.com/leandroBorgesFerreira/LoadingButtonAndroid/tree/master ]
loading-button = "2.3.0"

# [ https://github.com/square/leakcanary ]
leakcanary-android = "2.12"

# [ https://github.com/guolindev/Glance ]
glance = "1.1.0"

# [ https://github.com/LuckSiege/PictureSelector ]
lucksiege-pictureselector = "v3.11.1"

# [ https://github.com/ReactiveX/RxAndroid --- https://github.com/ReactiveX/RxJava ]
rxjava3 = "3.1.8"
rxjava3-android = "3.0.2"

# [ https://insert-koin.io/ ]
koin-android = "3.5.0"

# [ https://github.com/airbnb/lottie-android ]
lottie = "6.1.0"

# [ https://github.com/Baseflow/PhotoView ]
photoview = "2.0.0"

# [ https://github.com/scwang90/SmartRefreshLayout ]
smartrefresh = "2.0.5"

glide = "5.0.0-rc01"


[libraries]
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines-core" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-common = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-js = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-js", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "network-retrofit" }
retrofit-converter-scalar = { group = "com.squareup.retrofit2", name = "converter-scalar", version.ref = "network-retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "network-retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "network-retrofit" }

okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "network-okhttp"}
okhttp-urlconnection = {group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "network-okhttp"}
okhttp-logging-interceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "network-okhttp"}

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "json-moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "json-moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "json-moshi" }

logger = {group = "com.orhanobut", name = "logger", version.ref = "logger" }

loading-button = { group = "com.github.leandroborgesferreira", name = "loading-button-android", version.ref = "loading-button" }

leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary-android" }
glance = { group = "com.guolindev.glance", name = "glance", version.ref = "glance" }

luksiege-picture-selector = { group = "io.github.lucksiege", name = "pictureselector", version.ref = "lucksiege-pictureselector" }
luksiege-compress = { group = "io.github.lucksiege", name = "compress", version.ref = "lucksiege-pictureselector" }
luksiege-ucrop = { group = "io.github.lucksiege", name = "ucrop", version.ref = "lucksiege-pictureselector" }
luksiege-camerax = { group = "io.github.lucksiege", name = "camerax", version.ref = "lucksiege-pictureselector" }

reactivex-rxjava3 = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava3" }
reactivex-rxjava3-rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxjava3-android" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-android" }
koin-androidx-navigation = { group = "io.insert-koin", name = "koin-androidx-navigation", version.ref = "koin-android" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin-android" }
koin-android-test = { group = "io.insert-koin", name = "koin-android-test", version.ref = "koin-android" }

lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }

refresh-layout-kernel = { group = "io.github.scwang90", name = "refresh-layout-kernel", version.ref = "smartrefresh" }
refresh-header-classics = { group = "io.github.scwang90", name = "refresh-header-classics", version.ref = "smartrefresh" }
refresh-header-material = { group = "io.github.scwang90", name = "refresh-header-material", version.ref = "smartrefresh" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }